name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v3

    # Step 2: Create and activate virtual environment
    - name: Setup Python virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install pytest

    # Step 3: List files to confirm path
    - name: List repository files
      run: ls -R

    # Step 4: Run tests
    - name: Run pytest
      run: |
        source venv/bin/activate
        # Adjust the path if your test file is in 'src' folder
        python -m pytest src/addition.py
