name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v3

    # Step 2: Install Python dependencies
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install pytest

    # Step 3: Run tests
    - name: Run tests
      run: |
        # If your code is in 'src' folder, uncomment next line
        # cd src
        python3 -m pytest addition.py
