name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v3

    # Step 2: Create and activate a virtual environment
    - name: Setup Python virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install pytest

    # Step 3: List repository files to confirm file locations
    - name: List repository files
      run: ls -R

    # Step 4: Run tests
    - name: Run pytest
      run: |
        source venv/bin/activate
        # Adjust path if addition.py is inside a folder like 'src'
        python -m pytest src/addition.py
