name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        python-version: [3.12.3]

    steps:
    - uses: actions/checkout@v3

    - name: Install Python 3.9
      run: |
        sudo apt-get update
        sudo apt-get install -y python3.9 python3.9-venv python3.9-dev python3-pip
        python3.9 --version

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install pytest

    - name: Run tests
      run: python3 -m pytest addition.py
